"""Owner-local tuning constants for the legacy Variant 1.4 detector."""

RESIZE_WIDTH = 1280
BLUR_KSIZE = 5
MIN_AREA = 50
MAX_AREA = 1200
MIN_WIDTH = 2
MIN_HEIGHT = 2
MAX_WIDTH_RATIO = 0.12
MAX_HEIGHT_RATIO = 0.12
MIN_FILL_RATIO = 0.10
ASPECT_RATIO_MIN = 0.20
ASPECT_RATIO_MAX = 5.50
MORPH_OPEN = 3
MORPH_CLOSE = 5
WARMUP_FRAMES = 40
OVERLOAD_MASK_COVERAGE_THRESHOLD = 0.85
OVERLOAD_CANDIDATE_COUNT_THRESHOLD = 250

MOG2_HISTORY = 350
MOG2_VAR_THRESHOLD = 18

GUIDE_MIN_CONFIRMED_HITS = 2
GUIDE_MAX_MISSED_FRAMES = 4
GUIDE_MAX_MATCH_DISTANCE = 42.0
GUIDE_FAST_DISTANCE_MULTIPLIER = 2.8
GUIDE_BOOTSTRAP_DISTANCE_MULTIPLIER = 2.8
GUIDE_MISSED_DISTANCE_BONUS = 0.45
GUIDE_VELOCITY_EMA_ALPHA = 0.55
GUIDE_SINGLE_CANDIDATE_REACQUIRE_GATE = 720.0

MIN_CURRENT_CONTRAST = 5.0
CONTRAST_CONTEXT_PAD = 8
THIN_LINE_MAX_SHORT_SIDE = 10
THIN_LINE_MIN_LONG_TO_SHORT = 3.0
REACQUIRE_MIN_CONTRAST = 6.0
REACQUIRE_MIN_AREA = 18
REACQUIRE_MAX_AREA_MULTIPLIER = 1.75
REACQUIRE_MIN_WINDOW_RADIUS = 96.0
REACQUIRE_MAX_WINDOW_RADIUS = 280.0
REACQUIRE_BLUR_KSIZE = 31
REACQUIRE_BODY_OPEN_KSIZE = 7
BODY_PRESENT_MIN_AREA = 300
BODY_PRESENT_MIN_SHORT_SIDE = 16
TINY_ARTIFACT_MAX_AREA = 180
TINY_ARTIFACT_MAX_SHORT_SIDE = 13
GLOBAL_BODY_SCAN_MAX_WIDTH = 640
