"""Internal tuning for the baseline Vision SimpleTracker."""

CONFIRMATION_MATCHES = 2
MAX_CONSECUTIVE_MISSES = 3
MATCHED_HISTORY_LENGTH = 5
MAX_ASSOCIATION_DISTANCE_PX = 120.0
MAX_BBOX_SIZE_RATIO = 3.0
DISTANCE_COST_WEIGHT = 0.60
IOU_COST_WEIGHT = 0.25
SIZE_COST_WEIGHT = 0.15
