"""PC-side Turret protocol, session, HAL, and control stack."""

from .controller import (
    ControllerError,
    ControllerModeError,
    ControllerStateError,
    PendingMotion,
    TurretController,
)
from .hal import HalError, RelativeMoveLimitError, TurretHal
from .pid import AxisPid, PidGains
from .protocol import (
    CommandCode,
    MoveRelativePayload,
    ProtocolRequest,
    ProtocolResponse,
    ResultCode,
    SetBaudratePayload,
    SetConfigPayload,
    SetVelocityPayload,
    crc16_modbus,
    decode_request,
    decode_response,
    encode_request,
    encode_response,
)
from .session import (
    BaudRecoveryError,
    EmergencyRetryExhaustedError,
    SessionBlockedError,
    SessionBusyError,
    SessionError,
    SessionResult,
    SessionRetryExhaustedError,
    SessionTransportError,
    TurretSession,
)
from .transport import (
    PhysicalTransport,
    SerialTransport,
    TransportDisconnectedError,
    TransportError,
    TransportIOError,
    TransportTimeoutError,
)

__all__ = [
    "AxisPid",
    "BaudRecoveryError",
    "CommandCode",
    "ControllerError",
    "ControllerModeError",
    "ControllerStateError",
    "EmergencyRetryExhaustedError",
    "HalError",
    "MoveRelativePayload",
    "PendingMotion",
    "PhysicalTransport",
    "PidGains",
    "ProtocolRequest",
    "ProtocolResponse",
    "RelativeMoveLimitError",
    "ResultCode",
    "SerialTransport",
    "SessionBlockedError",
    "SessionBusyError",
    "SessionError",
    "SessionResult",
    "SessionRetryExhaustedError",
    "SessionTransportError",
    "SetBaudratePayload",
    "SetConfigPayload",
    "SetVelocityPayload",
    "TransportDisconnectedError",
    "TransportError",
    "TransportIOError",
    "TransportTimeoutError",
    "TurretController",
    "TurretHal",
    "TurretSession",
    "crc16_modbus",
    "decode_request",
    "decode_response",
    "encode_request",
    "encode_response",
]
